[package]
name = "scJaccard"
version = "0.1.0"
authors = ["Christopher Cole <ccole@well.ox.ac.uk>"]
edition = "2018"

[dependencies]
structopt = "0.3.14"
log = "0.4"
env_logger = "0.7.1"
rust-htslib = "*"
rayon = "1.1"
